// Generates worker/src/skills.bundle.js from skills/*/SKILL.md so the Worker
// embeds the exact checked-in skill texts. Run: node worker/build-skills.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "skills");
const names = readdirSync(root, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name).sort();
const bundles = names.map(name => {
  const text = readFileSync(join(root, name, "SKILL.md"), "utf8");
  return { name, text };
});
const out = `// AUTO-GENERATED by worker/build-skills.mjs — do not edit by hand.\nexport const SKILL_BUNDLES = ${JSON.stringify(bundles, null, 2)};\n`;
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "src", "skills.bundle.js"), out);
console.log(`wrote skills.bundle.js with ${bundles.length} skills: ${names.join(", ")}`);
